apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller-operatorsdk-take2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sample-controller-operatorsdk-take2
  template:
    metadata:
      labels:
        name: sample-controller-operatorsdk-take2
    spec:
      serviceAccountName: sample-controller-operatorsdk-take2
      containers:
        - name: sample-controller-operatorsdk-take2
          # Replace this with the built image name
          image: yukihirop/foo-controller:operatorsdk
          command:
          - sample-controller-operatorsdk-take2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sample-controller-operatorsdk-take2"
