kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-controller-operatorsdk-take2
subjects:
- kind: ServiceAccount
  name: sample-controller-operatorsdk-take2
roleRef:
  kind: Role
  name: sample-controller-operatorsdk-take2
  apiGroup: rbac.authorization.k8s.io
